indentAfterHeadings:
  part:
    indent: 1
    level: 0
  chapter:
    indent: 1
    level: 1
  section:
    indent: 1
    level: 3
  subsection:
    indent: 1
    level: 3
  subsection*:
    indent: 1
    level: 4
  subsubsection:
    indent: 1
    level: 5
  paragraph:
    indent: 1
    level: 6
  subparagraph:
    indent: 1
    level: 7
indentRules:
   item: "      "
noAdditionalIndent:
   ifnum: 0
   ifodd: 0
#defaultIndent: " "
indentAfterItems:
    itemize: 1
itemNames:
    item: 1
    myitem: 1
onlyOneBackUp: 1
cycleThroughBackUps: 1
maxNumberOfBackUps: 0
constructIfElseFi:
    if@isu@draftcls@: 1
    if@isu@capstoc: 1
    if@isu@tocnumbersections@: 1
    if@isu@errormissingmainmatter@: 1
lookForAlignDelims:
  align: 0
logFilePreferences:
    showAmalgamatedSettings: 0
    traceModeDecreaseIndent: '--'
    traceModeIncreaseIndent: '++'
    traceModeAddCurrentIndent: '&&&&'
    traceModeBetweenLines: "\n\n"
    endLogFileWith: "\n--------------\n****"
