lookForAlignDelims:
   article: 
      delimiterRegEx: '(=)'
   book: 
      delimiterRegEx: '(=)'
   online: 
      delimiterRegEx: '(?<!v)(?<!spfreload)(=)'

fineTuning:
    keyEqualsValuesBracesBrackets:
      follow: '(?:(?<!\\)\{)|(?:(?<!\\)\[)'
    UnNamedGroupingBracesBrackets: 
      follow: '\{|\[|,|&|\)|\(|\$|='
