name: Create and publish latexindent.exe and documentation latexindent.pdf to releases
# PURPOSE:
#
#  1. *create* latexindent.exe using PAR::Packer on Strawberry Perl
#  2. *publish* latexindent.exe to the most recent tag (release)
#  3. *create* latexindent.pdf 
#  4. *create* latexindent.zip
#  5. *publish* latexindent.zip to the most recent tag (release)
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  build-latexindent-doc-pdf:
    name: 'latexindent.pdf documentation creation using arara on texlive'
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing texlive full
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add openjdk11
            github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
            github_branch="main"
            github_release=$(echo ${{ github.ref }}|cut -d'/' -f 3)
            sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitBranch/main/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitRel/$github_release/ documentation/latexindent.tex
            sed -i.bak "s|\\\\gitAuthorDate|$(date +'%Y-%m-%d')|g" documentation/latexindent.tex
            sed -i.bak s/\\\\gitRel/$github_release/ documentation/sec-introduction.tex
            cd documentation
            arara -v latexindent.tex
            cd ..
            mkdir -p target/release
            mv documentation/latexindent.pdf target/release
      # upload latexindent.pdf to the artifact
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      - name: uploading latexindent.pdf
        uses: actions/upload-artifact@master
        with:
          name: latexindent.pdf
          path: target/release
  build-windows-exe:
    name: 'latexindent.exe creation using Strawberry Perl 5.32 on Windows'
    runs-on: 'windows-latest'
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      # install Strawberry Perl
      #
      # https://github.com/marketplace/actions/setup-perl-environment
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry
      # create latexindent.exe using Par::Packer
      #
      - name: creating latexindent.exe
        run: |
          cpanm -f PAR::Packer
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
          copy helper-scripts/ppp.pl ./
          perl ppp.pl -o latexindent.exe latexindent.pl
          mkdir -p target/release
          mv latexindent.exe target/release
      # upload latexindent.exe to the artifact
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      - name: uploading latexindent.exe
        uses: actions/upload-artifact@master
        with:
          name: latexindent.exe
          path: target/release
      # copy latexindent.exe to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload latexindent.exe to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/latexindent.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
  zip-files:
    name: 'Creating latexindent.zip and uploading to release'
    needs: [build-latexindent-doc-pdf, build-windows-exe]
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v2
      - name: copying files from repository into temporary folder
        run: |
          mkdir latexindent
          cp latexindent.pl latexindent/
          cp defaultSettings.yaml latexindent/
          cp -r LatexIndent latexindent/
          cp helper-scripts/latexindent-module-installer.pl latexindent/
          mkdir latexindent/documentation/
          cp documentation/*.tex latexindent/documentation/
          cp documentation/*.png latexindent/documentation/
          cp documentation/readme.txt latexindent/README
          cp documentation/*.json latexindent/documentation/
      - name: downloading latexindent.exe
        uses: actions/download-artifact@master
        with:
          name: latexindent.exe
          path: latexindent/
      - name: downloading latexindent.pdf
        uses: actions/download-artifact@master
        with:
          name: latexindent.pdf
          path: latexindent/documentation/
      - name: creating latexindent.zip
        run: |
          zip -r latexindent.zip latexindent/
      # copy latexindent.zip to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload latexindent.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latexindent.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
